return {
    ["Aleoida Arcus"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Maximum gravity: 0.27",
            "Mean temperature between 175 K and 180 K",
        },
        variant_headers = {},
        variant_mapping = {},
    },
    ["Aleoida Coronamus"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Maximum gravity: 0.27",
            "Mean temperature between 180 K and 190 K",
        },
        variant_headers = {},
        variant_mapping = {},
    },
    ["Aleoida Gravis"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Maximum gravity: 0.27",
            "Mean temperature between 190 K and 195 K",
        },
        variant_headers = {},
        variant_mapping = {},
    },
    ["Aleoida Laminiae"] = {
        conditions = {
            "Planets with thin Ammonia atmosphere",
            "Maximum gravity: 0.27",
        },
        variant_headers = {},
        variant_mapping = {},
    },
    ["Aleoida Spica"] = {
        conditions = {
            "Planets with thin Ammonia atmosphere",
            "Maximum gravity: 0.27",
        },
        variant_headers = {},
        variant_mapping = {},
    },
    ["Bacterium Acies"] = {
        conditions = {
            "Planet with thin Neon or Neon-rich atmosphere",
        },
        variant_headers = {
            "GRADE 4 RAW MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Antimony = "Cyan",
            Polonium = "Magenta",
            Ruthenium = "Cobalt",
            Technetium = "Lime",
            Tellurium = "White",
            Yttrium = "Aquamarine",
        },
        variant_method = "grade_4_material",
    },
    ["Bacterium Alcyoneum"] = {
        conditions = {
            "Planet with thin Ammonia atmosphere",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Yellow",
            B = "Grey",
            D = "Ocher",
            F = "Lime",
            G = "Emerald",
            K = "Green",
            L = "Sage",
            M = "Teal",
            N = "Indigo",
            O = "Turquoise",
            T = "Red",
            TTS = "Maroon",
            W = "Amethyst",
            Y = "Mauve",
        },
        variant_method = "star",
    },
    ["Bacterium Aurasus"] = {
        conditions = {
            "Planet with thin Carbon Dioxide atmosphere",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Yellow",
            B = "Grey",
            D = "Ocher",
            F = "Lime",
            G = "Emerald",
            K = "Green",
            L = "Sage",
            M = "Teal",
            N = "Indigo",
            O = "Turquoise",
            T = "Red",
            TTS = "Maroon",
            W = "Amethyst",
            Y = "Mauve",
        },
        variant_method = "star",
    },
    ["Bacterium Bullaris"] = {
        conditions = {
            "Planet with thin Methane or Methane-rich atmosphere",
        },
        variant_headers = {
            "GRADE 4 RAW MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Antimony = "Cobalt",
            Polonium = "Yellow",
            Ruthenium = "Aquamarine",
            Technetium = "Gold",
            Tellurium = "Lime",
            Yttrium = "Red",
        },
        variant_method = "grade_4_material",
    },
    ["Bacterium Cerbrus"] = {
        conditions = {
            "Planet with thin Water of Sulfur Dioxide atmosphere",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Yellow",
            B = "Grey",
            D = "Ocher",
            F = "Lime",
            G = "Emerald",
            K = "Green",
            L = "Sage",
            M = "Teal",
            N = "Indigo",
            O = "Turquoise",
            T = "Red",
            TTS = "Maroon",
            W = "Amethyst",
            Y = "Mauve",
        },
        variant_method = "star",
    },
    ["Bacterium Informem"] = {
        conditions = {
            "Planet with thin Nitrogen atmosphere",
        },
        variant_headers = {
            "GRADE 4 RAW MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Antimony = "Red",
            Polonium = "Lime",
            Ruthenium = "Gold",
            Technetium = "Aquamarine",
            Tellurium = "Yellow",
            Yttrium = "Cobalt",
        },
        variant_method = "grade_4_material",
    },
    ["Bacterium Nebulus"] = {
        conditions = {
            "Planet with thin Helium atmosphere",
        },
        variant_headers = {
            "GRADE 4 RAW MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Antimony = "Magenta",
            Polonium = "Gold",
            Ruthenium = "Orange",
            Tellurium = "Green",
            Yttrium = "Cobalt",
        },
        variant_method = "grade_4_material",
    },
    ["Bacterium Omentum"] = {
        conditions = {
            "Planets with thin Neon or Neon-rich atmosphere",
            "Nitrogen or Ammonia based Volcanism",
        },
        variant_headers = {
            "GRADE 3 RAW MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Cadmium = "Lime",
            Mercury = "White",
            Molybdenum = "Aquamarine",
            Niobium = "Peach",
            Tin = "Red",
            Tungsten = "Blue",
        },
        variant_method = "grade_3_material",
    },
    ["Bacterium Scopulum"] = {
        conditions = {
            "Planets with thin Neon or Neon-rich atmosphere",
            "Carbon or Methane based volcanism",
        },
        variant_headers = {
            "GRADE 3 RAW MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Cadmium = "White",
            Mercury = "Peach",
            Molybdenum = "Lime",
            Niobium = "Red",
            Tin = "Mulberry",
            Tungsten = "Aquamarine",
        },
        variant_method = "grade_3_material",
    },
    ["Bacterium Tela"] = {
        conditions = {
            "Planets with thin atmosphere",
            "Helium, Iron, Silicate or Ammonia based volcanism",
        },
        variant_headers = {
            "GRADE 3 RAW MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Cadmium = "Gold",
            Mercury = "Orange",
            Molybdenum = "Yellow",
            Niobium = "Magenta",
            Tin = "Cobalt",
            Tungsten = "Green",
        },
        variant_method = "grade_3_material",
    },
    ["Bacterium Verrata"] = {
        conditions = {
            "Planets with thin Neon or Neon-rich atmosphere",
            "Water based volcanism",
        },
        variant_headers = {
            "GRADE 3 RAW MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Cadmium = "Peach",
            Mercury = "Red",
            Molybdenum = "White",
            Niobium = "Mulberry",
            Tin = "Blue",
            Tungsten = "Lime",
        },
        variant_method = "grade_3_material",
    },
    ["Bacterium Vesicula"] = {
        conditions = {
            "Planet with thin Argon atmosphere",
        },
        variant_headers = {
            "GRADE 4 RAW MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Antimony = "Cyan",
            Polonium = "Orange",
            Ruthenium = "Mulberry",
            Technetium = "Gold",
            Tellurium = "Red",
            Yttrium = "Lime",
        },
        variant_method = "grade_4_material",
    },
    ["Bacterium Volu"] = {
        conditions = {
            "Planet with thin Oxygen atmosphere",
        },
        variant_headers = {
            "GRADE 4 RAW MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Antimony = "Red",
            Polonium = "Aquamarine",
            Ruthenium = "Cobalt",
            Tellurium = "Cyan",
            Yttrium = "Gold",
        },
        variant_method = "grade_4_material",
    },
    ["Cactoida Cortexum"] = {
        conditions = {
            "Planets with thin Carbon Dioxide atmosphere",
            "Maximum gravity: 0.27",
            "Mean temperature between 180 K and 195 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Green",
            D = "Turquoise",
            F = "Yellow",
            G = "Teal",
            L = "Mauve",
            M = "Amethyst",
            N = "Sage",
            O = "Grey",
            T = "Orange",
            TTS = "Red",
            W = "Indigo",
            Y = "Ocher",
        },
        variant_method = "star",
    },
    ["Cactoida Lapis"] = {
        conditions = {
            "Planets with thin Ammonia atmosphere",
            "Maximum gravity : 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Green",
            D = "Turquoise",
            F = "Yellow",
            G = "Teal",
            L = "Mauve",
            M = "Amethyst",
            N = "Sage",
            O = "Grey",
            T = "Orange",
            TTS = "Red",
            W = "Indigo",
            Y = "Ocher",
        },
        variant_method = "star",
    },
    ["Cactoida Peperatis"] = {
        conditions = {
            "Planets with thin Ammonia atmosphere",
            "Maximum gravity : 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Green",
            D = "Turquoise",
            F = "Yellow",
            G = "Teal",
            L = "Mauve",
            M = "Amethyst",
            N = "Sage",
            O = "Grey",
            T = "Orange",
            TTS = "Red",
            W = "Indigo",
            Y = "Ocher",
        },
        variant_method = "star",
    },
    ["Cactoida Pullulanta"] = {
        conditions = {
            "Planets with thin Carbon Dioxide atmosphere",
            "Maximum gravity : 0.27",
            "Mean temperature between 180 K and 195 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Green",
            D = "Turquoise",
            F = "Yellow",
            G = "Teal",
            L = "Mauve",
            M = "Amethyst",
            N = "Sage",
            O = "Grey",
            T = "Orange",
            TTS = "Red",
            W = "Indigo",
            Y = "Ocher",
        },
        variant_method = "star",
    },
    ["Cactoida Vermis"] = {
        conditions = {
            "Planets with thin Water atmosphere",
            "Maximum gravity : 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Green",
            D = "Turquoise",
            F = "Yellow",
            G = "Teal",
            L = "Mauve",
            M = "Amethyst",
            N = "Sage",
            O = "Grey",
            T = "Orange",
            TTS = "Red",
            W = "Indigo",
            Y = "Ocher",
        },
        variant_method = "star",
    },
    ["Clypeus Lacrimam"] = {
        conditions = {
            "Planets with thin Carbon Dioxide or Water atmosphere",
            "Maximum gravity : 0.27",
            "Mean temperature superior to 190 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Orange",
            B = "Maroon",
            D = "Lime",
            F = "Mauve",
            G = "Amethyst",
            K = "Grey",
            L = "Teal",
            M = "Turquoise",
            N = "Yellow",
            Y = "Green",
        },
        variant_method = "star",
    },
    ["Clypeus Margaritus"] = {
        conditions = {
            "Planets with thin Carbon Dioxide or Water atmosphere",
            "Maximum gravity : 0.27",
            "Mean temperature superior to 190 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Orange",
            B = "Maroon",
            D = "Lime",
            F = "Mauve",
            G = "Amethyst",
            K = "Grey",
            L = "Teal",
            M = "Turquoise",
            N = "Yellow",
            Y = "Green",
        },
        variant_method = "star",
    },
    ["Clypeus Speculumi"] = {
        conditions = {
            "Planets with thin Carbon Dioxide or Water atmosphere",
            "Maximum gravity : 0.27",
            "Mean temperature superior to 190 K",
            "Distance from parent star must be superior to 2 500 LS (5 AU)",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Orange",
            B = "Maroon",
            D = "Lime",
            F = "Mauve",
            G = "Amethyst",
            K = "Grey",
            L = "Teal",
            M = "Turquoise",
            N = "Yellow",
            Y = "Green",
        },
        variant_method = "star",
    },
    ["Colored Variants"] = {
        conditions = {},
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Concha Aureolas"] = {
        conditions = {
            "Planet with thin Ammonia atmosphere",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Teal",
            B = "Indigo",
            F = "Grey",
            G = "Turquoise",
            K = "Red",
            L = "Orange",
            N = "Emerald",
            Y = "Yellow",
        },
        variant_method = "star",
    },
    ["Concha Biconcavis"] = {
        conditions = {
            "Planet with thin Nitrogen atmosphere",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Antinomy = "Peach",
            Polonium = "Red",
            Ruthenium = "Orange",
            Tellurium = "Yellow",
        },
        variant_method = "rare_material",
    },
    ["Concha Labiata"] = {
        conditions = {
            "Planet with thin Carbon Dioxide atmosphere",
            "Maximum gravity: 0.27",
            "Mean temperature inferior to 190 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Teal",
            B = "Indigo",
            F = "Grey",
            G = "Turquoise",
            K = "Red",
            L = "Orange",
            N = "Emerald",
            W = "Lime",
            Y = "Yellow",
        },
        variant_method = "star",
    },
    ["Concha Renibus"] = {
        conditions = {
            "Planet with thin Carbon Dioxide or Water atmosphere",
            "Maximum gravity: 0.27",
            "For Carbon dioxide, mean temperature between 180 K and 195 K",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Cadmium = "Red",
            Mercury = "Mulberry",
            Molybdenum = "Peach",
            Niobium = "Blue",
            Tin = "Aquamarine",
            Tungsten = "White",
        },
        variant_method = "rare_material",
    },
    ["Conditions Of Occurrence"] = {
        conditions = {
            "Planets with thin atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "ATMOSPHERE TYPE",
            "SPECIES",
        },
        variant_mapping = {
            Ammonia = "Tussock Catena\
Tussock Cultro\
Tussock Divisa",
            ["Carbon dioxide\
Carbon dioxide rich"] = "Tussock Propagito (< 195 K)\
Tussock Pennatis (< 195 K)\
Tussock Pennata (145 k - 155 K)\
Tussock Ventusa (155 K - 160 K)\
Tussock Ignis (160 K - 170 K)\
Tussock Serrati (170 K - 175 K)\
Tussock Albata (175 K - 180 K)\
Tussock Caputus (180 K - 190 K)\
Tussock Triticum (190K - 195 K)",
            ["Methane, Methane-rich\
Argon, Argon-rich"] = "Tussock Capillum",
            ["Suphur dioxide"] = "Tussock Stigmasis",
            ["Water, Water-rich"] = "Tussock Virgam",
        },
        variant_method = "star",
    },
    ["Electricae Pluma"] = {
        conditions = {
            "Planet with thin Helium, Neon or Argon atmosphere",
            "Icy planets",
            "Parent star of type A, with a luminosity class of V or more, Neutron star, White dwarf, or Black hole. To be confirmed: type O, B.",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Antinomy = "Cobalt",
            Polonium = "Cyan",
            Ruthenium = "Blue",
            Technetium = "Magenta",
            Tellurium = "Red",
            Yttrium = "Mulberry",
        },
        variant_method = "rare_material",
    },
    ["Electricae Radialem"] = {
        conditions = {
            "Planet with thin Helium, Neon, Argon or Nitrogen atmosphere",
            "Icy planets",
            "Close to Nebulae",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Antinomy = "Cyan",
            Polonium = "Cobalt",
            Ruthenium = "Blue",
            Technetium = "Aquamarine",
            Tellurium = "Magenta",
            Yttrium = "Green",
        },
        variant_method = "rare_material",
    },
    ["Fonticulua Campestris"] = {
        conditions = {
            "Planets with thin Argon atmosphere",
            "Icy or Rocky Ice planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Green",
            ["Ae/Be"] = "Maroon",
            B = "Lime",
            D = "Turquoise",
            F = "Yellow",
            G = "Teal",
            K = "Emerald",
            L = "Mauve",
            M = "Amethyst",
            N = "Sage",
            O = "Grey",
            T = "Orange",
            TTS = "Red",
            W = "Indigo",
            Y = "Ocher",
        },
        variant_method = "star",
    },
    ["Fonticulua Digitos"] = {
        conditions = {
            "Planets with thin Methane or Methane rich atmosphere",
            "Icy or Rocky Ice planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Green",
            ["Ae/Be"] = "Maroon",
            B = "Lime",
            D = "Turquoise",
            F = "Yellow",
            G = "Teal",
            K = "Emerald",
            L = "Mauve",
            M = "Amethyst",
            N = "Sage",
            O = "Grey",
            T = "Orange",
            TTS = "Red",
            W = "Indigo",
            Y = "Ocher",
        },
        variant_method = "star",
    },
    ["Fonticulua Fluctus"] = {
        conditions = {
            "Planet with thin Oxygen atmosphere",
            "Icy or Rocky Ice planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Green",
            ["Ae/Be"] = "Maroon",
            B = "Lime",
            D = "Turquoise",
            F = "Yellow",
            G = "Teal",
            K = "Emerald",
            L = "Mauve",
            M = "Amethyst",
            N = "Sage",
            O = "Grey",
            T = "Orange",
            TTS = "Red",
            W = "Indigo",
            Y = "Ocher",
        },
        variant_method = "star",
    },
    ["Fonticulua Lapida"] = {
        conditions = {
            "Planet with thin Nitrogen atmosphere",
            "Icy or Rocky Ice planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Green",
            ["Ae/Be"] = "Maroon",
            B = "Lime",
            D = "Turquoise",
            F = "Yellow",
            G = "Teal",
            K = "Emerald",
            L = "Mauve",
            M = "Amethyst",
            N = "Sage",
            O = "Grey",
            T = "Orange",
            TTS = "Red",
            W = "Indigo",
            Y = "Ocher",
        },
        variant_method = "star",
    },
    ["Fonticulua Segmentatus"] = {
        conditions = {
            "Planet with thin Neon or Neon-rich atmosphere",
            "Icy or Rocky Ice planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Green",
            ["Ae/Be"] = "Maroon",
            B = "Lime",
            D = "Turquoise",
            F = "Yellow",
            G = "Teal",
            K = "Emerald",
            L = "Mauve",
            M = "Amethyst",
            N = "Sage",
            O = "Grey",
            T = "Orange",
            TTS = "Red",
            W = "Indigo",
            Y = "Ocher",
        },
        variant_method = "star",
    },
    ["Fonticulua Upupam"] = {
        conditions = {
            "Planet with thin Argon-rich atmosphere",
            "Icy or Rocky Ice planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Green",
            ["Ae/Be"] = "Maroon",
            B = "Lime",
            D = "Turquoise",
            F = "Yellow",
            G = "Teal",
            K = "Emerald",
            L = "Mauve",
            M = "Amethyst",
            N = "Sage",
            O = "Grey",
            T = "Orange",
            TTS = "Red",
            W = "Indigo",
            Y = "Ocher",
        },
        variant_method = "star",
    },
    ["Frutexa Acus"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
            "Mean temperature inferior to 195 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            B = "Lime",
            D = "Indigo",
            F = "Green",
            G = "Emerald",
            L = "Teal",
            M = "Grey",
            N = "Red",
            O = "Yellow",
            TTS = "Mauve",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Frutexa Collum"] = {
        conditions = {
            "Planets with thin Sulphur dioxide atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            B = "Lime",
            D = "Indigo",
            F = "Green",
            G = "Emerald",
            L = "Teal",
            M = "Grey",
            N = "Red",
            O = "Yellow",
            TTS = "Mauve",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Frutexa Fera"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
            "Mean temperature inferior to 195 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            B = "Lime",
            D = "Indigo",
            F = "Green",
            G = "Emerald",
            L = "Teal",
            M = "Grey",
            N = "Red",
            O = "Yellow",
            TTS = "Mauve",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Frutexa Flabellum"] = {
        conditions = {
            "Planets with thin Ammonia atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            B = "Lime",
            D = "Indigo",
            F = "Green",
            G = "Emerald",
            L = "Teal",
            M = "Grey",
            N = "Red",
            O = "Yellow",
            TTS = "Mauve",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Frutexa Flammasis"] = {
        conditions = {
            "Planets with thin Ammonia atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            B = "Lime",
            D = "Indigo",
            F = "Green",
            G = "Emerald",
            L = "Teal",
            M = "Grey",
            N = "Red",
            O = "Yellow",
            TTS = "Mauve",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Frutexa Metallicum"] = {
        conditions = {
            "Planets with thin Carbon dioxide or Ammonia atmosphere",
            "High Metal Content planets",
            "For Carbon dioxide atmosperes, mean temperature inferior to 195 K",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            B = "Lime",
            D = "Indigo",
            F = "Green",
            G = "Emerald",
            L = "Teal",
            M = "Grey",
            N = "Red",
            O = "Yellow",
            TTS = "Mauve",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Frutexa Sponsae"] = {
        conditions = {
            "Planets with thin Water atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            B = "Lime",
            D = "Indigo",
            F = "Green",
            G = "Emerald",
            L = "Teal",
            M = "Grey",
            N = "Red",
            O = "Yellow",
            TTS = "Mauve",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Fumerola Aquatis"] = {
        conditions = {
            "Planets with thin atmosphere",
            "Develop on fumaroles (geological POI)",
            "Water based volcanism, only on Icy or Rocky Ice planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Cadmium = "Green",
            Mercury = "Yellow",
            Molybdenum = "Cyan",
            Niobium = "Gold",
            Tin = "Orange",
            Tungsten = "Cobalt",
        },
        variant_method = "rare_material",
    },
    ["Fumerola Carbosis"] = {
        conditions = {
            "Planets with thin atmosphere",
            "Develop on fumaroles (geological POI)",
            "Carbon or Methane based volcanism, only on Icy or Rocky Ice planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Cadmium = "Orange",
            Mercury = "Magenta",
            Molybdenum = "Gold",
            Niobium = "Cobalt",
            Tin = "Teal",
            Tungsten = "Yellow",
        },
        variant_method = "rare_material",
    },
    ["Fumerola Extremus"] = {
        conditions = {
            "Planets with thin atmosphere",
            "Develop on fumaroles (geological POI)",
            "Silicate, Iron or Rocky based volcanism, only on Rocky or High Metal Content planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Mercury = "Lime",
            Molybdenum = "Blue",
            Niobium = "White",
            Tin = "Peach",
            Tungsten = "Mulberry",
        },
        variant_method = "rare_material",
    },
    ["Fumerola Nitris"] = {
        conditions = {
            "Planets with thin atmosphere",
            "Develop on fumaroles (geological POI)",
            "Nitrogen or Ammonia based volcanism, only on Icy or Rocky Ice planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Cadmium = "White",
            Mercury = "Peach",
            Molybdenum = "Lime",
            Niobium = "Red",
            Tin = "Mulberry",
            Tungsten = "Aquamarine",
        },
        variant_method = "rare_material",
    },
    ["Fungoida Bullarum"] = {
        conditions = {
            "Planets with thin Argon or Argon-rich atmosphere",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Antinomy = "Red",
            Polonium = "Mulberry",
            Ruthenium = "Magenta",
            Technetium = "Peach",
            Tellurium = "Gold",
            Yttrium = "Orange",
        },
        variant_method = "rare_material",
    },
    ["Fungoida Gelata"] = {
        conditions = {
            "Planets with thin Carbon Dioxide or Water atmosphere",
            "Maximum gravity: 0.27",
            "For Carbon Dioxide atmospheres, mean temperature between 180 K and 195 K",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Cadmium = "Cyan",
            Mercury = "Lime",
            Molybdenum = "Mulberry",
            Niobium = "Green",
            Tin = "Red",
            Tungsten = "Orange",
        },
        variant_method = "rare_material",
    },
    ["Fungoida Setisis"] = {
        conditions = {
            "Planets with thin Ammonia or Methane atmosphere",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Antinomy = "Peach",
            Polonium = "White",
            Ruthenium = "Gold",
            Technetium = "Lime",
            Tellurium = "Yellow",
            Yttrium = "Orange",
        },
        variant_method = "rare_material",
    },
    ["Fungoida Stabilis"] = {
        conditions = {
            "Planets with thin Carbon dioxide or Water atmosphere",
            "Maximum gravity: 0.27",
            "For Carbon Dioxide atmospheres, mean temperature between 180 K and 195 K",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Cadmium = "Blue",
            Mercury = "Green",
            Molybdenum = "Magenta",
            Niobium = "White",
            Tin = "Orange",
            Tungsten = "Peach",
        },
        variant_method = "rare_material",
    },
    ["Osseus Cornibus"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Only on Rocky or High Metal Content planets",
            "Only present on rocky areas on planets",
            "Maximum gravity: 0.27",
            "Mean temperature between 180 K and 195 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Lime",
            F = "Turquoise",
            G = "Grey",
            K = "Indigo",
            T = "Emerald",
            TTS = "Green",
        },
        variant_method = "star",
    },
    ["Osseus Discus"] = {
        conditions = {
            "Planets with thin Water atmosphere",
            "Only on Rocky or High Metal Content planets",
            "Only present on rocky areas on planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Cadmium = "White",
            Mercury = "Lime",
            Molybdenum = "Peach",
            Niobium = "Aquamarine",
            Tin = "Blue",
            Tungsten = "Red",
        },
        variant_method = "rare_material",
    },
    ["Osseus Fractus"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Only on Rocky or High Metal Content planets",
            "Only present on rocky areas on planets",
            "Maximum gravity: 0.27",
            "Mean temperature between 180 K and 195 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Lime",
            F = "Turquoise",
            G = "Grey",
            K = "Indigo",
            T = "Emerald",
            TTS = "Green",
            Y = "Maroon",
        },
        variant_method = "star",
    },
    ["Osseus Pellebantus"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Only on Rocky or High Metal Content planets",
            "Only present on rocky areas on planets",
            "Maximum gravity: 0.27",
            "Mean temperature between 180 K and 195 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Lime",
            F = "Turquoise",
            G = "Grey",
            K = "Indigo",
            T = "Emerald",
            TTS = "Green",
            Y = "Maroon",
        },
        variant_method = "star",
    },
    ["Osseus Pumice"] = {
        conditions = {
            "Planets with thin Argon, Methane or Nitrogen atmosphere",
            "Only on Rocky, High Metal Content or Rocky Ice planets",
            "Only present on rocky areas on planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Antinomy = "White",
            Polonium = "Peach",
            Ruthenium = "Gold",
            Technetium = "Lime",
            Tellurium = "Green",
            Yttrium = "Yellow",
        },
        variant_method = "rare_material",
    },
    ["Osseus Spiralis"] = {
        conditions = {
            "Planets with thin Ammonia atmosphere",
            "Only on Rocky or High Metal Content planets",
            "Only present on rocky areas on planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Lime",
            F = "Turquoise",
            G = "Grey",
            K = "Indigo",
            O = "Yellow",
            T = "Emerald",
            TTS = "Green",
            Y = "Maroon",
        },
        variant_method = "star",
    },
    ["Recepta Conditivus"] = {
        conditions = {
            "Planet with thin Sulfur Dioxide atmosphere",
            "Icy or Rocky Ice planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Antinomy = "Lime",
            Polonium = "White",
            Technetium = "Aquamarine",
            Tellurium = "Cyan",
            Yttrium = "Green",
        },
        variant_method = "rare_material",
    },
    ["Recepta Deltahedronix"] = {
        conditions = {
            "Planet with thin Sulfur Dioxide atmosphere",
            "Rocky or High Metal Content planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "MATERIAL",
            "COLOR",
        },
        variant_mapping = {
            Cadmium = "Lime",
            Mercury = "Gold",
            Molybdenum = "Orange",
            Niobium = "Mulberry",
            Tungsten = "Red",
        },
        variant_method = "rare_material",
    },
    ["Recepta Umbrux"] = {
        conditions = {
            "Planet with thin Sulfur Dioxide atmosphere",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            A = "Amethyst",
            B = "Turquoise",
            D = "Yellow",
            F = "Mauve",
            G = "Orange",
            K = "Red",
            L = "Ocher",
            M = "Maroon",
            N = "Emerald",
            T = "Teal",
            TTS = "Sage",
        },
        variant_method = "star",
    },
    ["Stratum Araneamus"] = {
        conditions = {
            "Planets with thin Sulphur dioxide atmosphere",
            "Rocky planets",
            "Mean temperature superior to 165 K",
        },
        variant_headers = {
            "PLANET TYPE",
            "ATMOSPHERE TYPE",
            "SPECIES",
        },
        variant_mapping = {
            ["Carbon dioxide\
Carbon dioxide rich"] = "Stratum paleas (> 165 K)\
Stratum excutitus (165 K - 190 K) \
Stratum limaxus (165 K - 190 K) \
Stratum frigus (> 190 K) \
Stratum cucumisis (> 190 K)",
            ["High Metal Content"] = "Oxygen\
Ammonia\
Water\
Water-rich\
Carbon dioxide\
Carbon dioxide rich\
Sulphur dioxide",
            Rocky = "Ammonia",
            ["Water\
Water-rich"] = "Stratum paleas",
        },
        variant_method = "star",
    },
    ["Stratum Cucumisis"] = {
        conditions = {
            "Planets with thin Sulfur Dioxide or Carbon Dioxide atmosphere",
            "Rocky planets",
            "Mean temperature superior to 190 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            D = "Mauve",
            F = "Emerald",
            K = "Lime",
            L = "Turquoise",
            M = "Green",
            T = "Grey",
            TTS = "Amethyst",
            W = "Red",
            Y = "Indigo",
        },
        variant_method = "star",
    },
    ["Stratum Excutitus"] = {
        conditions = {
            "Planets with thin Sulfur Dioxide or Carbon Dioxide atmosphere",
            "Rocky planets",
            "Mean temperature between 165 K and 190 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            D = "Mauve",
            F = "Emerald",
            K = "Lime",
            L = "Turquoise",
            M = "Green",
            T = "Grey",
            TTS = "Amethyst",
            W = "Red",
            Y = "Indigo",
        },
        variant_method = "star",
    },
    ["Stratum Frigus"] = {
        conditions = {
            "Planets with thin Sulfur Dioxide or Carbon Dioxide atmosphere",
            "Rocky planets",
            "Mean temperature superior to 190 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            D = "Mauve",
            F = "Emerald",
            K = "Lime",
            L = "Turquoise",
            M = "Green",
            T = "Grey",
            TTS = "Amethyst",
            W = "Red",
            Y = "Indigo",
        },
        variant_method = "star",
    },
    ["Stratum Laminamus"] = {
        conditions = {
            "Planets with thin Ammonia atmosphere",
            "Rocky planets",
            "Mean temperature superior to 165 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            D = "Mauve",
            F = "Emerald",
            K = "Lime",
            L = "Turquoise",
            M = "Green",
            T = "Grey",
            TTS = "Amethyst",
            W = "Red",
            Y = "Indigo",
        },
        variant_method = "star",
    },
    ["Stratum Limaxus"] = {
        conditions = {
            "Planets with thin Sulfur Dioxide or Carbon Dioxide atmosphere",
            "Rocky planets",
            "Mean temperature between 165 K and 190 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            D = "Mauve",
            F = "Emerald",
            K = "Lime",
            L = "Turquoise",
            M = "Green",
            T = "Grey",
            TTS = "Amethyst",
            W = "Red",
            Y = "Indigo",
        },
        variant_method = "star",
    },
    ["Stratum Paleas"] = {
        conditions = {
            "Planets with thin Ammonia, Water or Carbon Dioxide atmosphere",
            "Rocky planets",
            "Mean temperature superior to 165 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            D = "Mauve",
            F = "Emerald",
            K = "Lime",
            L = "Turquoise",
            M = "Green",
            T = "Grey",
            TTS = "Amethyst",
            W = "Red",
            Y = "Indigo",
        },
        variant_method = "star",
    },
    ["Stratum Tectonicas"] = {
        conditions = {
            "Planets with thin atmosphere",
            "High Metal Content planets",
            "Mean temperature superior to 165 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            D = "Mauve",
            F = "Emerald",
            K = "Lime",
            L = "Turquoise",
            M = "Green",
            T = "Grey",
            TTS = "Amethyst",
            W = "Red",
            Y = "Indigo",
        },
        variant_method = "star",
    },
    ["Tubus Cavas"] = {
        conditions = {
            "Planets with thin CO₂ atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.15",
            "Mean temperature: 160 K - 190 K",
        },
        variant_headers = {},
        variant_mapping = {},
    },
    ["Tubus Compagibus"] = {
        conditions = {
            "Planets with thin CO₂ atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.15",
            "Mean temperature: 160 K - 190 K",
        },
        variant_headers = {},
        variant_mapping = {},
    },
    ["Tubus Conifer"] = {
        conditions = {
            "Planets with thin CO₂ atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.15",
            "Mean temperature: 160 K - 190 K",
        },
        variant_headers = {},
        variant_mapping = {},
    },
    ["Tubus Rosarium"] = {
        conditions = {
            "Planets with thin Ammonia atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.15",
            "Mean temperature: >160 K",
        },
        variant_headers = {},
        variant_mapping = {},
    },
    ["Tubus Sororibus"] = {
        conditions = {
            "Planets with thin CO₂ or Ammonia atmosphere",
            "High Metal Content planets",
            "Maximum gravity: 0.15",
            "Mean temperature: 160 K - 190 K",
        },
        variant_headers = {},
        variant_mapping = {},
    },
    ["Tussock Albata"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
            "Mean temperature between 175 K and 180 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Tussock Capillum"] = {
        conditions = {
            "Planets with thin Argon or Methane atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Tussock Caputus"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
            "Mean temperature between 180 K and 190 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Tussock Catena"] = {
        conditions = {
            "Planets with thin Ammonia atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Tussock Cultro"] = {
        conditions = {
            "Planets with thin Ammonia atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Tussock Divisa"] = {
        conditions = {
            "Planets with thin Ammonia atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Tussock Ignis"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
            "Mean temperature between 160 K and 170 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Tussock Pennata"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
            "Mean temperature between 145 K and 155 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Tussock Pennatis"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
            "Mean temperature inferior to 195 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Tussock Propagito"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
            "Mean temperature inferior to 195 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Tussock Serrati"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
            "Mean temperature between 170 K and 175 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Tussock Stigmasis"] = {
        conditions = {
            "Planets with thin Sulphur dioxide atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Tussock Triticum"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
            "Mean temperature between 190 K and 195 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Tussock Ventusa"] = {
        conditions = {
            "Planets with thin Carbon dioxide atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
            "Mean temperature between 155 K and 160 K",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
    ["Tussock Virgam"] = {
        conditions = {
            "Planets with thin Water atmosphere",
            "Rocky planets",
            "Maximum gravity: 0.27",
        },
        variant_headers = {
            "STAR TYPE",
            "COLOR",
        },
        variant_mapping = {
            ["Black Hole"] = "Red",
            D = "Maroon",
            F = "Yellow",
            G = "Lime",
            K = "Green",
            L = "Sage",
            M = "Emerald",
            T = "Teal",
            W = "Orange",
        },
        variant_method = "star",
    },
}
